spring:
  profiles:
    include: key


server:
  servlet:
    encoding:
      force-response: true
  port: 9999

springdoc:
  swagger-ui:
    path: /
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

