version: '3.8'

services:

  slack-collection-db:
    container_name: slack-collection-db
    image: mariadb:10.8.3
    user: "mysql:${GID}"
    ports:
      - "9995:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: "sc-db"
    volumes:
      - ./conf/my.conf:/etc/mysql/my.cnf
      - ./logs/db:/home/mysql/log
